package com.voxeldev.canoe.compose.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF00639A)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFCEE5FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001D32)
internal val md_theme_light_secondary = Color(0xFF51606F)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD5E4F7)
internal val md_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
internal val md_theme_light_tertiary = Color(0xFF68587A)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFEEDBFF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF231533)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFCFCFF)
internal val md_theme_light_onBackground = Color(0xFF1A1C1E)
internal val md_theme_light_surface = Color(0xFFFCFCFF)
internal val md_theme_light_onSurface = Color(0xFF1A1C1E)
internal val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
internal val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
internal val md_theme_light_outline = Color(0xFF72777F)
internal val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
internal val md_theme_light_inverseSurface = Color(0xFF2F3033)
internal val md_theme_light_inversePrimary = Color(0xFF96CCFF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF00639A)
internal val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF96CCFF)
internal val md_theme_dark_onPrimary = Color(0xFF003353)
internal val md_theme_dark_primaryContainer = Color(0xFF004A75)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFCEE5FF)
internal val md_theme_dark_secondary = Color(0xFFB9C8DA)
internal val md_theme_dark_onSecondary = Color(0xFF233240)
internal val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD5E4F7)
internal val md_theme_dark_tertiary = Color(0xFFD3BFE6)
internal val md_theme_dark_onTertiary = Color(0xFF382A49)
internal val md_theme_dark_tertiaryContainer = Color(0xFF4F4061)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFEEDBFF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1A1C1E)
internal val md_theme_dark_onBackground = Color(0xFFE2E2E5)
internal val md_theme_dark_surface = Color(0xFF1A1C1E)
internal val md_theme_dark_onSurface = Color(0xFFE2E2E5)
internal val md_theme_dark_surfaceVariant = Color(0xFF42474E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
internal val md_theme_dark_outline = Color(0xFF8C9198)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
internal val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
internal val md_theme_dark_inversePrimary = Color(0xFF00639A)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF96CCFF)
internal val md_theme_dark_outlineVariant = Color(0xFF42474E)
internal val md_theme_dark_scrim = Color(0xFF000000)

internal val seed = Color(0xFF527DA4)
