name: Android workflow

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies
      - name: Checkstyle
        run: ./gradlew detektAll
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        if: failure()
        with:
          name: detekt.html
          path: build/reports/detekt/detekt.html

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create google-services.json
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: echo $DATA > /home/runner/work/Canoe/Canoe/canoe/src/google-services.json
      - name: Create secrets.properties
        env:
          DATA: ${{secrets.SECRETS_PROPERTIES}}
        run: echo $DATA > /home/runner/work/Canoe/Canoe/secrets.properties
      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      - name: Generate test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  app_distribution:
    runs-on: ubuntu-latest
    needs:
      - detekt
      - unit_tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create google-services.json
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: echo $DATA > /home/runner/work/Canoe/Canoe/canoe/src/google-services.json
      - name: Create secrets.properties
        env:
          DATA: ${{secrets.SECRETS_PROPERTIES}}
        run: echo $DATA > /home/runner/work/Canoe/Canoe/secrets.properties
      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies
      - name: Build release
        run: ./gradlew assembleRelease
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: canoe/build/outputs/apk/release/canoe-release-unsigned.apk
