name: detekt

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  app_distribution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create google-services.json
        run: cat /home/runner/work/Canoe/Canoe/canoe/src/google-services.json | base64
      - name: Put google-services.json data
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: echo $DATA > /home/runner/work/Canoe/Canoe/canoe/src/google-services.json
      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies
      - name: Build release
        run: ./gradlew assembleRelease
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
